services:
  sinamn75api:
    image: sinamn75api
    build: .
    ports:
      - "8090:80"
      - "8091:443"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+:443;http://+:80"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "BetterSoft1234"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/sinamn75api.pfx"
    volumes:
      - ~/.aspnet/https:/https:ro
      - /www/wwwroot/api.sinamn75.com/SinaMN75Api/wwwroot
      - /www/wwwroot/api.sinamn75.com/SinaMN75Api/wwwroot/Medias
      - /www/wwwroot/api.sinamn75.com/SinaMN75Api/wwwroot/Medias/users