services:
  sinamn75api:
    image: sinamn75api
    build: .
    ports:
      - "8085:80"
      - "8081:443"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+:443;http://+:80"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "BetterSoft1234"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnetapp.pfx"
    volumes:
      - ~/.aspnet/https:/https:ro