// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SinaMN75Api;

#nullable disable

namespace SinaMN75Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CategoryEntityGroupChatEntity", b =>
                {
                    b.Property<Guid>("CategoriesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupChatsId")
                        .HasColumnType("uuid");

                    b.HasKey("CategoriesId", "GroupChatsId");

                    b.HasIndex("GroupChatsId");

                    b.ToTable("CategoryEntityGroupChatEntity");
                });

            modelBuilder.Entity("CategoryEntityProductEntity", b =>
                {
                    b.Property<Guid>("CategoriesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductsId")
                        .HasColumnType("uuid");

                    b.HasKey("CategoriesId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("CategoryEntityProductEntity");
                });

            modelBuilder.Entity("CategoryEntityUserEntity", b =>
                {
                    b.Property<Guid>("CategoriesId")
                        .HasColumnType("uuid");

                    b.Property<string>("UsersId")
                        .HasColumnType("text");

                    b.HasKey("CategoriesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("CategoryEntityUserEntity");
                });

            modelBuilder.Entity("GroupChatEntityUserEntity", b =>
                {
                    b.Property<Guid>("GroupChatsId")
                        .HasColumnType("uuid");

                    b.Property<string>("UsersId")
                        .HasColumnType("text");

                    b.HasKey("GroupChatsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("GroupChatEntityUserEntity");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.AddressEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Pelak")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ReceiverFullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ReceiverPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.BookmarkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FolderName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookmarks");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.CategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<int[]>("Tags")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("integer[]");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TitleTr1")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TitleTr2")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.CommentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<double?>("Score")
                        .HasColumnType("double precision");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<int[]>("Tags")
                        .HasMaxLength(100)
                        .HasColumnType("integer[]");

                    b.Property<string>("TargetUserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("ProductId");

                    b.HasIndex("TargetUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.ContentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("SubTitle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int[]>("Tags")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("integer[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Contents");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.DiscountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DiscountPrice")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumberUses")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Discount");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.GroupChatEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatorUserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("GroupChat");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.GroupChatMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ForwardedMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GroupChatId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SeenUsersId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ForwardedMessageId");

                    b.HasIndex("GroupChatId");

                    b.HasIndex("ParentId");

                    b.HasIndex("SeenUsersId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupChatMessage");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.MediaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BookmarkId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CommentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("GroupChatId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GroupChatMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("NotificationId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int[]>("Tags")
                        .HasMaxLength(100)
                        .HasColumnType("integer[]");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BookmarkId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CommentId");

                    b.HasIndex("ContentId");

                    b.HasIndex("GroupChatId");

                    b.HasIndex("GroupChatMessageId");

                    b.HasIndex("NotificationId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.NotificationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatorUserId")
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SeenStatus")
                        .HasColumnType("integer");

                    b.Property<int[]>("Tags")
                        .HasMaxLength(100)
                        .HasColumnType("integer[]");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<bool?>("Visited")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.OrderDetailEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Count")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("FinalPrice")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<long?>("UnitPrice")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Vote")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetail");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.OrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeliverDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DiscountCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("DiscountPercent")
                        .HasColumnType("integer");

                    b.Property<long?>("DiscountPrice")
                        .HasColumnType("bigint");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PayDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ProductOwnerId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReceivedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("SendPrice")
                        .HasColumnType("bigint");

                    b.Property<int[]>("Tags")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<long?>("TotalPrice")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("ProductOwnerId");

                    b.HasIndex("UserId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.ProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AgeCategory")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Boosted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CommentsCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Currency")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("DiscountPercent")
                        .HasColumnType("integer");

                    b.Property<long?>("DiscountPrice")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GroupChatEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GroupChatMessageEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GroupChatMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<long?>("Price")
                        .HasColumnType("bigint");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SeenUsers")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("Stock")
                        .HasColumnType("integer");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int[]>("Tags")
                        .HasMaxLength(100)
                        .HasColumnType("integer[]");

                    b.Property<string>("Teams")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int?>("VoteCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GroupChatEntityId");

                    b.HasIndex("GroupChatMessageEntityId");

                    b.HasIndex("ParentId");

                    b.HasIndex("UserId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.ProductInsight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReactionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ReactionId");

                    b.HasIndex("UserId");

                    b.ToTable("ProductsInsight");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.PromotionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgeCategories")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayType")
                        .HasColumnType("integer");

                    b.Property<string>("Gender")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("GroupChatId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Skills")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("States")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("UserPromotedId")
                        .HasColumnType("text");

                    b.Property<string>("Users")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("GroupChatId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserPromotedId");

                    b.ToTable("Promotion");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.ReactionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChatsId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Reaction")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reaction");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.ReportEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CommentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatorUserId")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("GroupChatId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GroupChatMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("GroupChatId");

                    b.HasIndex("GroupChatMessageId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.SeenUsers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FkGroupChat")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FkGroupChatMessage")
                        .HasColumnType("uuid");

                    b.Property<string>("FkUserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SeenUsers");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.SubscriptionPaymentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("Amount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PayDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PromotionId")
                        .HasColumnType("uuid");

                    b.Property<int>("SubscriptionType")
                        .HasColumnType("integer");

                    b.Property<int>("Tag")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PromotionId");

                    b.HasIndex("UserId");

                    b.ToTable("SubscriptionPayment");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.TransactionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("Amount")
                        .HasColumnType("bigint");

                    b.Property<string>("CardNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descriptions")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("RefId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SubscriptionPaymentId")
                        .HasColumnType("uuid");

                    b.Property<int[]>("Tags")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("integer[]");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("SubscriptionPaymentId");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<int?>("AgeCategory")
                        .HasColumnType("integer");

                    b.Property<string>("AppEmail")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AppPhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("AppUserName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Badge")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BlockedUsers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BookmarkedProducts")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CommentCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ExpireUpgradeAccount")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FollowedUsers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FollowingUsers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("Headline")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool?>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean");

                    b.Property<string>("JobStatus")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MutedChats")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<double?>("Point")
                        .HasColumnType("double precision");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool?>("Suspend")
                        .HasColumnType("boolean");

                    b.Property<int[]>("Tags")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("VisitedProducts")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("Wallet")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.VisitProducts", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("VisitProducts");
                });

            modelBuilder.Entity("CategoryEntityGroupChatEntity", b =>
                {
                    b.HasOne("Utilities_aspnet.Entities.CategoryEntity", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Utilities_aspnet.Entities.GroupChatEntity", null)
                        .WithMany()
                        .HasForeignKey("GroupChatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CategoryEntityProductEntity", b =>
                {
                    b.HasOne("Utilities_aspnet.Entities.CategoryEntity", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Utilities_aspnet.Entities.ProductEntity", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CategoryEntityUserEntity", b =>
                {
                    b.HasOne("Utilities_aspnet.Entities.CategoryEntity", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Utilities_aspnet.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GroupChatEntityUserEntity", b =>
                {
                    b.HasOne("Utilities_aspnet.Entities.GroupChatEntity", null)
                        .WithMany()
                        .HasForeignKey("GroupChatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Utilities_aspnet.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.AddressEntity", b =>
                {
                    b.HasOne("Utilities_aspnet.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.BookmarkEntity", b =>
                {
                    b.HasOne("Utilities_aspnet.Entities.BookmarkEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.HasOne("Utilities_aspnet.Entities.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.HasOne("Utilities_aspnet.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Parent");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.CategoryEntity", b =>
                {
                    b.HasOne("Utilities_aspnet.Entities.CategoryEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.OwnsOne("Utilities_aspnet.Entities.CategoryJsonDetail", "JsonDetail", b1 =>
                        {
                            b1.Property<Guid>("CategoryEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("Boosted")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Color")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("Date1")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime?>("Date2")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<long?>("DiscountedPrice")
                                .HasColumnType("bigint");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("double precision");

                            b1.Property<string>("Link")
                                .HasColumnType("text");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("double precision");

                            b1.Property<long?>("Price")
                                .HasColumnType("bigint");

                            b1.Property<long?>("SendPrice")
                                .HasColumnType("bigint");

                            b1.Property<int?>("Stock")
                                .HasColumnType("integer");

                            b1.Property<string>("Subtitle")
                                .HasColumnType("text");

                            b1.Property<double?>("Value")
                                .HasColumnType("double precision");

                            b1.HasKey("CategoryEntityId");

                            b1.ToTable("Categories");

                            b1.ToJson("JsonDetail");

                            b1.WithOwner()
                                .HasForeignKey("CategoryEntityId");
                        });

                    b.Navigation("JsonDetail")
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.CommentEntity", b =>
                {
                    b.HasOne("Utilities_aspnet.Entities.CommentEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.HasOne("Utilities_aspnet.Entities.ProductEntity", "Product")
                        .WithMany("Comments")
                        .HasForeignKey("ProductId");

                    b.HasOne("Utilities_aspnet.Entities.UserEntity", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId");

                    b.HasOne("Utilities_aspnet.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.OwnsOne("Utilities_aspnet.Entities.CommentJsonDetail", "JsonDetail", b1 =>
                        {
                            b1.Property<Guid>("CommentEntityId")
                                .HasColumnType("uuid");

                            b1.HasKey("CommentEntityId");

                            b1.ToTable("Comment");

                            b1.ToJson("JsonDetail");

                            b1.WithOwner()
                                .HasForeignKey("CommentEntityId");

                            b1.OwnsMany("Utilities_aspnet.Entities.CommentReacts", "Reacts", b2 =>
                                {
                                    b2.Property<Guid>("CommentJsonDetailCommentEntityId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<int>("Reaction")
                                        .HasColumnType("integer");

                                    b2.Property<string>("UserId")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("CommentJsonDetailCommentEntityId", "Id");

                                    b2.ToTable("Comment");

                                    b2.WithOwner()
                                        .HasForeignKey("CommentJsonDetailCommentEntityId");
                                });

                            b1.Navigation("Reacts");
                        });

                    b.Navigation("JsonDetail")
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Product");

                    b.Navigation("TargetUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.ContentEntity", b =>
                {
                    b.OwnsOne("Utilities_aspnet.Entities.ContentJsonDetail", "JsonDetail", b1 =>
                        {
                            b1.Property<Guid>("ContentEntityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Address1")
                                .HasColumnType("text");

                            b1.Property<string>("Address2")
                                .HasColumnType("text");

                            b1.Property<string>("Address3")
                                .HasColumnType("text");

                            b1.Property<string>("Dribble")
                                .HasColumnType("text");

                            b1.Property<string>("Email1")
                                .HasColumnType("text");

                            b1.Property<string>("Email2")
                                .HasColumnType("text");

                            b1.Property<string>("Instagram")
                                .HasColumnType("text");

                            b1.Property<string>("LinkedIn")
                                .HasColumnType("text");

                            b1.Property<string>("PhoneNumber1")
                                .HasColumnType("text");

                            b1.Property<string>("PhoneNumber2")
                                .HasColumnType("text");

                            b1.Property<string>("Pinterest")
                                .HasColumnType("text");

                            b1.Property<string>("SoundCloud")
                                .HasColumnType("text");

                            b1.Property<string>("Telegram")
                                .HasColumnType("text");

                            b1.Property<string>("Website")
                                .HasColumnType("text");

                            b1.Property<string>("WhatsApp")
                                .HasColumnType("text");

                            b1.HasKey("ContentEntityId");

                            b1.ToTable("Contents");

                            b1.ToJson("JsonDetail");

                            b1.WithOwner()
                                .HasForeignKey("ContentEntityId");
                        });

                    b.Navigation("JsonDetail")
                        .IsRequired();
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.DiscountEntity", b =>
                {
                    b.HasOne("Utilities_aspnet.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.GroupChatEntity", b =>
                {
                    b.OwnsOne("Utilities_aspnet.Entities.GroupChatJsonDetail", "JsonDetail", b1 =>
                        {
                            b1.Property<Guid>("GroupChatEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("Boosted")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int?>("ChatStatus")
                                .HasColumnType("integer");

                            b1.Property<string>("Department")
                                .HasColumnType("text");

                            b1.Property<string>("Description")
                                .HasColumnType("text");

                            b1.Property<int?>("Priority")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .HasColumnType("text");

                            b1.HasKey("GroupChatEntityId");

                            b1.ToTable("GroupChat");

                            b1.ToJson("JsonDetail");

                            b1.WithOwner()
                                .HasForeignKey("GroupChatEntityId");
                        });

                    b.Navigation("JsonDetail")
                        .IsRequired();
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.GroupChatMessageEntity", b =>
                {
                    b.HasOne("Utilities_aspnet.Entities.GroupChatMessageEntity", "ForwardedMessage")
                        .WithMany()
                        .HasForeignKey("ForwardedMessageId");

                    b.HasOne("Utilities_aspnet.Entities.GroupChatEntity", "GroupChat")
                        .WithMany("GroupChatMessage")
                        .HasForeignKey("GroupChatId");

                    b.HasOne("Utilities_aspnet.Entities.GroupChatMessageEntity", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.HasOne("Utilities_aspnet.Entities.SeenUsers", "SeenUsers")
                        .WithMany()
                        .HasForeignKey("SeenUsersId");

                    b.HasOne("Utilities_aspnet.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("ForwardedMessage");

                    b.Navigation("GroupChat");

                    b.Navigation("Parent");

                    b.Navigation("SeenUsers");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.MediaEntity", b =>
                {
                    b.HasOne("Utilities_aspnet.Entities.BookmarkEntity", "Bookmark")
                        .WithMany("Media")
                        .HasForeignKey("BookmarkId");

                    b.HasOne("Utilities_aspnet.Entities.CategoryEntity", "Category")
                        .WithMany("Media")
                        .HasForeignKey("CategoryId");

                    b.HasOne("Utilities_aspnet.Entities.CommentEntity", "Comment")
                        .WithMany("Media")
                        .HasForeignKey("CommentId");

                    b.HasOne("Utilities_aspnet.Entities.ContentEntity", "Content")
                        .WithMany("Media")
                        .HasForeignKey("ContentId");

                    b.HasOne("Utilities_aspnet.Entities.GroupChatEntity", "GroupChat")
                        .WithMany("Media")
                        .HasForeignKey("GroupChatId");

                    b.HasOne("Utilities_aspnet.Entities.GroupChatMessageEntity", "GroupChatMessage")
                        .WithMany("Media")
                        .HasForeignKey("GroupChatMessageId");

                    b.HasOne("Utilities_aspnet.Entities.NotificationEntity", "Notification")
                        .WithMany("Media")
                        .HasForeignKey("NotificationId");

                    b.HasOne("Utilities_aspnet.Entities.ProductEntity", "Product")
                        .WithMany("Media")
                        .HasForeignKey("ProductId");

                    b.HasOne("Utilities_aspnet.Entities.UserEntity", "User")
                        .WithMany("Media")
                        .HasForeignKey("UserId");

                    b.OwnsOne("Utilities_aspnet.Entities.MediaJsonDetail", "JsonDetail", b1 =>
                        {
                            b1.Property<Guid>("MediaEntityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Album")
                                .HasColumnType("text");

                            b1.Property<string>("Artist")
                                .HasColumnType("text");

                            b1.Property<int?>("IsPrivate")
                                .HasColumnType("integer");

                            b1.Property<string>("Size")
                                .HasColumnType("text");

                            b1.Property<string>("Time")
                                .HasColumnType("text");

                            b1.Property<string>("Title")
                                .HasColumnType("text");

                            b1.HasKey("MediaEntityId");

                            b1.ToTable("Media");

                            b1.ToJson("JsonDetail");

                            b1.WithOwner()
                                .HasForeignKey("MediaEntityId");
                        });

                    b.Navigation("Bookmark");

                    b.Navigation("Category");

                    b.Navigation("Comment");

                    b.Navigation("Content");

                    b.Navigation("GroupChat");

                    b.Navigation("GroupChatMessage");

                    b.Navigation("JsonDetail")
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.NotificationEntity", b =>
                {
                    b.HasOne("Utilities_aspnet.Entities.UserEntity", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId");

                    b.HasOne("Utilities_aspnet.Entities.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.HasOne("Utilities_aspnet.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("CreatorUser");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.OrderDetailEntity", b =>
                {
                    b.HasOne("Utilities_aspnet.Entities.OrderEntity", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId");

                    b.HasOne("Utilities_aspnet.Entities.ProductEntity", "Product")
                        .WithMany("OrderDetail")
                        .HasForeignKey("ProductId");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.OrderEntity", b =>
                {
                    b.HasOne("Utilities_aspnet.Entities.AddressEntity", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("Utilities_aspnet.Entities.UserEntity", "ProductOwner")
                        .WithMany()
                        .HasForeignKey("ProductOwnerId");

                    b.HasOne("Utilities_aspnet.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.OwnsOne("Utilities_aspnet.Entities.OrderJsonDetail", "JsonDetail", b1 =>
                        {
                            b1.Property<Guid>("OrderEntityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ProductId")
                                .HasColumnType("text");

                            b1.HasKey("OrderEntityId");

                            b1.ToTable("Order");

                            b1.ToJson("JsonDetail");

                            b1.WithOwner()
                                .HasForeignKey("OrderEntityId");

                            b1.OwnsMany("Utilities_aspnet.Entities.OrderDetailHistory", "OrderDetailHistories", b2 =>
                                {
                                    b2.Property<Guid>("OrderJsonDetailOrderEntityId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<int?>("Count")
                                        .HasColumnType("integer");

                                    b2.Property<long?>("FinalPrice")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("ProductId")
                                        .HasColumnType("text");

                                    b2.Property<string>("Title")
                                        .HasColumnType("text");

                                    b2.Property<long?>("UnitPrice")
                                        .HasColumnType("bigint");

                                    b2.HasKey("OrderJsonDetailOrderEntityId", "Id");

                                    b2.ToTable("Order");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderJsonDetailOrderEntityId");
                                });

                            b1.OwnsMany("Utilities_aspnet.Entities.Seat", "Seats", b2 =>
                                {
                                    b2.Property<Guid>("OrderJsonDetailOrderEntityId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("ChairId")
                                        .HasColumnType("text");

                                    b2.Property<int?>("Column")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Date")
                                        .HasColumnType("text");

                                    b2.Property<string>("Description")
                                        .HasColumnType("text");

                                    b2.Property<int?>("Gender")
                                        .HasColumnType("integer");

                                    b2.Property<long?>("Price")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("ReservedByUserId")
                                        .HasColumnType("text");

                                    b2.Property<string>("ReservedByUserName")
                                        .HasColumnType("text");

                                    b2.Property<int?>("Row")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Salon")
                                        .HasColumnType("text");

                                    b2.Property<string>("Sans")
                                        .HasColumnType("text");

                                    b2.Property<int?>("Tag")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Title")
                                        .HasColumnType("text");

                                    b2.HasKey("OrderJsonDetailOrderEntityId", "Id");

                                    b2.ToTable("Order");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderJsonDetailOrderEntityId");
                                });

                            b1.OwnsMany("Utilities_aspnet.Entities.ReserveDto", "ReservationTimes", b2 =>
                                {
                                    b2.Property<Guid>("OrderJsonDetailOrderEntityId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<DateTime>("DateFrom")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<DateTime>("DateTo")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<int>("ExtraMemberCount")
                                        .HasColumnType("integer");

                                    b2.Property<int>("MemberCount")
                                        .HasColumnType("integer");

                                    b2.Property<long>("Price")
                                        .HasColumnType("bigint");

                                    b2.Property<long>("PriceForAnyExtra")
                                        .HasColumnType("bigint");

                                    b2.Property<Guid>("ProductId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("ReserveId")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("UserId")
                                        .HasColumnType("text");

                                    b2.Property<string>("UserName")
                                        .HasColumnType("text");

                                    b2.HasKey("OrderJsonDetailOrderEntityId", "Id");

                                    b2.ToTable("Order");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderJsonDetailOrderEntityId");
                                });

                            b1.Navigation("OrderDetailHistories");

                            b1.Navigation("ReservationTimes");

                            b1.Navigation("Seats");
                        });

                    b.Navigation("Address");

                    b.Navigation("JsonDetail")
                        .IsRequired();

                    b.Navigation("ProductOwner");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.ProductEntity", b =>
                {
                    b.HasOne("Utilities_aspnet.Entities.GroupChatEntity", null)
                        .WithMany("Products")
                        .HasForeignKey("GroupChatEntityId");

                    b.HasOne("Utilities_aspnet.Entities.GroupChatMessageEntity", "GroupChatMessageEntity")
                        .WithMany("Products")
                        .HasForeignKey("GroupChatMessageEntityId");

                    b.HasOne("Utilities_aspnet.Entities.ProductEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.HasOne("Utilities_aspnet.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.OwnsOne("Utilities_aspnet.Entities.ProductJsonDetail", "JsonDetail", b1 =>
                        {
                            b1.Property<Guid>("ProductEntityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Address")
                                .HasColumnType("text");

                            b1.Property<string>("AdminMessage")
                                .HasColumnType("text");

                            b1.Property<string>("Author")
                                .HasColumnType("text");

                            b1.Property<string>("Color")
                                .HasColumnType("text");

                            b1.Property<string>("Details")
                                .HasColumnType("text");

                            b1.Property<string>("Email")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("EndDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int?>("Height")
                                .HasColumnType("integer");

                            b1.Property<string>("KeyValue")
                                .HasColumnType("text");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("double precision");

                            b1.Property<int?>("Length")
                                .HasColumnType("integer");

                            b1.Property<string>("Link")
                                .HasColumnType("text");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("double precision");

                            b1.Property<long?>("MaxOrder")
                                .HasColumnType("bigint");

                            b1.Property<long?>("MaxPrice")
                                .HasColumnType("bigint");

                            b1.Property<int?>("MinOrder")
                                .HasColumnType("integer");

                            b1.Property<long?>("MinPrice")
                                .HasColumnType("bigint");

                            b1.Property<int?>("OnTimeDelivery")
                                .HasColumnType("integer");

                            b1.Property<string>("PhoneNumber")
                                .HasColumnType("text");

                            b1.Property<int?>("ResponseTime")
                                .HasColumnType("integer");

                            b1.Property<int?>("ShippingCost")
                                .HasColumnType("integer");

                            b1.Property<int?>("ShippingTime")
                                .HasColumnType("integer");

                            b1.Property<DateTime?>("StartDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Type1")
                                .HasColumnType("text");

                            b1.Property<string>("Type2")
                                .HasColumnType("text");

                            b1.Property<string>("Unit")
                                .HasColumnType("text");

                            b1.Property<string>("Website")
                                .HasColumnType("text");

                            b1.Property<int?>("Weight")
                                .HasColumnType("integer");

                            b1.Property<int?>("Width")
                                .HasColumnType("integer");

                            b1.HasKey("ProductEntityId");

                            b1.ToTable("Products");

                            b1.ToJson("JsonDetail");

                            b1.WithOwner()
                                .HasForeignKey("ProductEntityId");

                            b1.OwnsMany("Utilities_aspnet.Entities.KeyValue", "KeyValues", b2 =>
                                {
                                    b2.Property<Guid>("ProductJsonDetailProductEntityId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("Key")
                                        .HasColumnType("text");

                                    b2.Property<string>("Value")
                                        .HasColumnType("text");

                                    b2.HasKey("ProductJsonDetailProductEntityId", "Id");

                                    b2.ToTable("Products");

                                    b2.WithOwner()
                                        .HasForeignKey("ProductJsonDetailProductEntityId");
                                });

                            b1.OwnsMany("Utilities_aspnet.Entities.Seat", "Seats", b2 =>
                                {
                                    b2.Property<Guid>("ProductJsonDetailProductEntityId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("ChairId")
                                        .HasColumnType("text");

                                    b2.Property<int?>("Column")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Date")
                                        .HasColumnType("text");

                                    b2.Property<string>("Description")
                                        .HasColumnType("text");

                                    b2.Property<int?>("Gender")
                                        .HasColumnType("integer");

                                    b2.Property<long?>("Price")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("ReservedByUserId")
                                        .HasColumnType("text");

                                    b2.Property<string>("ReservedByUserName")
                                        .HasColumnType("text");

                                    b2.Property<int?>("Row")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Salon")
                                        .HasColumnType("text");

                                    b2.Property<string>("Sans")
                                        .HasColumnType("text");

                                    b2.Property<int?>("Tag")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Title")
                                        .HasColumnType("text");

                                    b2.HasKey("ProductJsonDetailProductEntityId", "Id");

                                    b2.ToTable("Products");

                                    b2.WithOwner()
                                        .HasForeignKey("ProductJsonDetailProductEntityId");
                                });

                            b1.OwnsMany("Utilities_aspnet.Entities.ReservationTime", "ReservationTimes", b2 =>
                                {
                                    b2.Property<Guid>("ProductJsonDetailProductEntityId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<DateTime?>("DateFrom")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<DateTime?>("DateTo")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<int?>("MaxExtraMemberAllowed")
                                        .HasColumnType("integer");

                                    b2.Property<int?>("MaxMemberAllowed")
                                        .HasColumnType("integer");

                                    b2.Property<long?>("Price")
                                        .HasColumnType("bigint");

                                    b2.Property<long?>("PriceForAnyExtra")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("ReserveId")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("ReservedByUserId")
                                        .HasColumnType("text");

                                    b2.Property<string>("ReservedByUserName")
                                        .HasColumnType("text");

                                    b2.HasKey("ProductJsonDetailProductEntityId", "Id");

                                    b2.ToTable("Products");

                                    b2.WithOwner()
                                        .HasForeignKey("ProductJsonDetailProductEntityId");
                                });

                            b1.OwnsMany("Utilities_aspnet.Entities.VisitCount", "VisitCounts", b2 =>
                                {
                                    b2.Property<Guid>("ProductJsonDetailProductEntityId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<int>("Count")
                                        .HasColumnType("integer");

                                    b2.Property<string>("UserId")
                                        .HasColumnType("text");

                                    b2.Property<string>("VisitId")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("ProductJsonDetailProductEntityId", "Id");

                                    b2.ToTable("Products");

                                    b2.WithOwner()
                                        .HasForeignKey("ProductJsonDetailProductEntityId");
                                });

                            b1.Navigation("KeyValues");

                            b1.Navigation("ReservationTimes");

                            b1.Navigation("Seats");

                            b1.Navigation("VisitCounts");
                        });

                    b.Navigation("GroupChatMessageEntity");

                    b.Navigation("JsonDetail")
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.ProductInsight", b =>
                {
                    b.HasOne("Utilities_aspnet.Entities.ProductEntity", "Product")
                        .WithMany("ProductInsights")
                        .HasForeignKey("ProductId");

                    b.HasOne("Utilities_aspnet.Entities.ReactionEntity", "Reaction")
                        .WithMany()
                        .HasForeignKey("ReactionId");

                    b.HasOne("Utilities_aspnet.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Product");

                    b.Navigation("Reaction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.PromotionEntity", b =>
                {
                    b.HasOne("Utilities_aspnet.Entities.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("Utilities_aspnet.Entities.GroupChatEntity", "GroupChat")
                        .WithMany()
                        .HasForeignKey("GroupChatId");

                    b.HasOne("Utilities_aspnet.Entities.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.HasOne("Utilities_aspnet.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.HasOne("Utilities_aspnet.Entities.UserEntity", "UserPromoted")
                        .WithMany()
                        .HasForeignKey("UserPromotedId");

                    b.Navigation("Category");

                    b.Navigation("GroupChat");

                    b.Navigation("Product");

                    b.Navigation("User");

                    b.Navigation("UserPromoted");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.ReactionEntity", b =>
                {
                    b.HasOne("Utilities_aspnet.Entities.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.HasOne("Utilities_aspnet.Entities.UserEntity", "User")
                        .WithMany("Reactions")
                        .HasForeignKey("UserId");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.ReportEntity", b =>
                {
                    b.HasOne("Utilities_aspnet.Entities.CommentEntity", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId");

                    b.HasOne("Utilities_aspnet.Entities.UserEntity", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId");

                    b.HasOne("Utilities_aspnet.Entities.GroupChatEntity", "GroupChat")
                        .WithMany()
                        .HasForeignKey("GroupChatId");

                    b.HasOne("Utilities_aspnet.Entities.GroupChatMessageEntity", "GroupChatMessage")
                        .WithMany()
                        .HasForeignKey("GroupChatMessageId");

                    b.HasOne("Utilities_aspnet.Entities.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.HasOne("Utilities_aspnet.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Comment");

                    b.Navigation("CreatorUser");

                    b.Navigation("GroupChat");

                    b.Navigation("GroupChatMessage");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.SubscriptionPaymentEntity", b =>
                {
                    b.HasOne("Utilities_aspnet.Entities.PromotionEntity", "Promotion")
                        .WithMany()
                        .HasForeignKey("PromotionId");

                    b.HasOne("Utilities_aspnet.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Promotion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.TransactionEntity", b =>
                {
                    b.HasOne("Utilities_aspnet.Entities.OrderEntity", "Order")
                        .WithMany("Transactions")
                        .HasForeignKey("OrderId");

                    b.HasOne("Utilities_aspnet.Entities.SubscriptionPaymentEntity", "SubscriptionPayment")
                        .WithMany()
                        .HasForeignKey("SubscriptionPaymentId");

                    b.HasOne("Utilities_aspnet.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Order");

                    b.Navigation("SubscriptionPayment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.UserEntity", b =>
                {
                    b.OwnsOne("Utilities_aspnet.Entities.UserJsonDetail", "JsonDetail", b1 =>
                        {
                            b1.Property<string>("UserEntityId")
                                .HasColumnType("text");

                            b1.Property<string>("Activity")
                                .HasColumnType("text");

                            b1.Property<string>("Address")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("Boosted")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Code")
                                .HasColumnType("text");

                            b1.Property<string>("Color")
                                .HasColumnType("text");

                            b1.Property<long?>("DeliveryPrice1")
                                .HasColumnType("bigint");

                            b1.Property<long?>("DeliveryPrice2")
                                .HasColumnType("bigint");

                            b1.Property<long?>("DeliveryPrice3")
                                .HasColumnType("bigint");

                            b1.Property<string>("Dribble")
                                .HasColumnType("text");

                            b1.Property<string>("FcmToken")
                                .HasColumnType("text");

                            b1.Property<string>("Instagram")
                                .HasColumnType("text");

                            b1.Property<int?>("LegalAuthenticationType")
                                .HasColumnType("integer");

                            b1.Property<string>("LinkedIn")
                                .HasColumnType("text");

                            b1.Property<int?>("NationalityType")
                                .HasColumnType("integer");

                            b1.Property<string>("Pinterest")
                                .HasColumnType("text");

                            b1.Property<int?>("PrivacyType")
                                .HasColumnType("integer");

                            b1.Property<string>("ShebaNumber")
                                .HasColumnType("text");

                            b1.Property<string>("SoundCloud")
                                .HasColumnType("text");

                            b1.Property<string>("Telegram")
                                .HasColumnType("text");

                            b1.Property<string>("Website")
                                .HasColumnType("text");

                            b1.Property<string>("WhatsApp")
                                .HasColumnType("text");

                            b1.HasKey("UserEntityId");

                            b1.ToTable("Users");

                            b1.ToJson("JsonDetail");

                            b1.WithOwner()
                                .HasForeignKey("UserEntityId");
                        });

                    b.Navigation("JsonDetail")
                        .IsRequired();
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.VisitProducts", b =>
                {
                    b.HasOne("Utilities_aspnet.Entities.ProductEntity", "Product")
                        .WithMany("VisitProducts")
                        .HasForeignKey("ProductId");

                    b.HasOne("Utilities_aspnet.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.BookmarkEntity", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.CategoryEntity", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.CommentEntity", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.ContentEntity", b =>
                {
                    b.Navigation("Media");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.GroupChatEntity", b =>
                {
                    b.Navigation("GroupChatMessage");

                    b.Navigation("Media");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.GroupChatMessageEntity", b =>
                {
                    b.Navigation("Media");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.NotificationEntity", b =>
                {
                    b.Navigation("Media");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.OrderEntity", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.ProductEntity", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Comments");

                    b.Navigation("Media");

                    b.Navigation("OrderDetail");

                    b.Navigation("ProductInsights");

                    b.Navigation("VisitProducts");
                });

            modelBuilder.Entity("Utilities_aspnet.Entities.UserEntity", b =>
                {
                    b.Navigation("Media");

                    b.Navigation("Reactions");
                });
#pragma warning restore 612, 618
        }
    }
}
