name: .NET

on:
  push:
    branches: [ DirectShod ]
  pull_request:
    branches: [ DirectShod ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: build and deploy docker image
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /www/wwwroot/api.directshod.com
            git pull https://SinaMN75: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@github.com/SinaMN75/SinaMN75Api_aspnet.git
            git submodule update --remote -f
            docker-compose stop
            docker-compose rm -f
            docker-compose up -d --build --force-recreate
            /etc/init.d/nginx restart
          host: 45.139.11.86
          user: root
          pass: BetterSoft1234