name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: build and deploy docker image
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 82.115.20.41
          username: root
          password: BetterSoft1234
          port: 22
          script: |
            cd /www/wwwroot/api.sinamn75.com
            git pull https://SinaMN75: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@github.com/SinaMN75/SinaMN75Api_aspnet.git
            git submodule update --remote -f
            docker-compose stop
            docker-compose up -d --build --force-recreate --scale sinamn75api=2
            /etc/init.d/nginx restart
          