name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x
      - name: Init Utilities
        run: git submodule update --init
      - name: Get Utilities
        run: git submodule update --remote -f
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Publish
        run: dotnet publish -c Release
      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          local-dir: SinaMN75Api/bin/Release/net7.0/publish/
          server: 45.139.11.86
          username: SinaMN75Api_aspnet
          password: BetterSoft1234!@#$
  
